spring.application.name=demo
# \u7AEF\u53E3
server.port=8081

# \u6570\u636E\u5E93\u914D\u7F6E
## \u8FDE\u63A5\u5730\u5740
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/user_db?useSSL=false&serverTimezone=UTC
## \u7528\u6237\u540D
spring.datasource.username=root
## \u5BC6\u7801
spring.datasource.password=root

# Hibernatep\u914D\u7F6E
## \u81EA\u52A8\u66F4\u65B0
spring.jpa.hibernate.ddl-auto=update
## \u63A7\u5236\u53F0\u8F93\u51FASQL\u8BED\u53E5, \u65B9\u4FBF\u8C03\u8BD5
spring.jpa.show-sql=true
## \u65B9\u8A00 mysql
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Redis \u914D\u7F6E
## \u4E3B\u673Aip
spring.data.redis.host=127.0.0.1
## \u7AEF\u53E3
spring.data.redis.port=6379
## \u7528\u6237
## spring.data.redis.username=user
## \u5BC6\u7801
## spring.data.redis.password=root
## \u8D85\u65F6\u65F6\u95F4
spring.data.redis.timeout=5000
## \u6700\u5927\u8FDE\u63A5\u6570
spring.data.redis.lettuce.pool.max-active=20
## \u6700\u5927\u963B\u585E\u7B49\u5F85\u65F6\u95F4(\u8D1F\u6570\u8868\u793A\u6CA1\u9650\u5236)
spring.data.redis.lettuce.pool.max-wait=-1
## \u6700\u5927\u7A7A\u95F2
spring.data.redis.lettuce.pool.max-idle=5
## \u6700\u5C0F\u7A7A\u95F2
spring.data.redis.lettuce.pool.min-idle=0
